apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitor-url.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{- include "monitor-url.name" . | nindent 6 }}
